name: Spring boot multitenancy
rating: 5
imageUrl: https://github.com/msa-ez/template-spring-boot-3/assets/123912988/e24335cf-0aec-429b-ab1b-0980a92926b7
templateName: spring-boot-multitenancy
description: Spring boot multitenancy description
