forEach: BoundedContext
fileName: application.yml
path: {{name}}/src/main/resources
ifDuplicated: merge
---
spring:
  profiles: default
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop  
    # properties:
    #   hibernate:
    #     show_sql: true
    #     format_sql: true
