forEach: BoundedContext
fileName: application.yml
path: {{name}}/src/main/resources
ifDuplicated: merge
---
spring:
  jpa:
    _key: 'database'
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
