spring:
  profiles: default
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop  
    # properties:
    #   hibernate:
    #     show_sql: true
    #     format_sql: true
